### ISSUE TITLE
Problem with fragile frames

### ISSUE THREAD

**Issue by Hepek93** [piazzai/arguelles#8] opened 2024-02-20 07:24 UTC
Dear @piazzai,

Your theme is great, so I need help to solve a problem.

When I used lstlisting in a presentation, I had to define the frame as fragile and that created a problem.
If the frame is defined as fragile, the text retains the background color of the frame.
I checked changing the background color and it affects the text color

If the frame is defined as standout, I can clearly see the text on the slide.

Interestingly, if I use your theme on overleaf everything works like a charm (text color is normal), but if I use it offline and compile it from pdflatex, it's a problem.

Thank you!

**Comment by piazzai** [comment] 2024-02-20 09:28
Hi @Hepek93, great to know you like the theme.

I'd like to help, but I don't know lstlisting so I have a couple of questions. (1) Do you _have to_ define the frame as fragile? As in, the correct use of lstlisting requires you to use a fragile frame? (2) Can you provide a MWE of the behavior you find problematic? If I manage to reproduce the problem I can look into it.

**Comment by Hepek93** [comment] 2024-02-20 23:39
Thank you @piazzai,

Here is basic example:
```
\documentclass[aspectratio=169]{beamer}
\usepackage{xcolor}
\usepackage{listings}

\usetheme{Arguelles}

\definecolor{main-dark}{rgb}{0.6627, 0.7176, 0.7764}
\definecolor{back-dark}{rgb}{0.1686, 0.1686, 0.1686}
\definecolor{string-dark}{rgb}{0.8, 0.47, 0.196}
\definecolor{key-dark}{RGB}{53, 131, 213}
\definecolor{comment-dark}{RGB}{77,166,66} 

\lstdefinestyle{darkcode}{
language=Python,
basicstyle=\small\ttfamily,
numbers=left,
numbersep=10pt,
xleftmargin=20pt,
frame=tb,
framexleftmargin=20pt,
commentstyle=\color{comment-dark},
backgroundcolor = {\color{back-dark}},
stringstyle = {\color{string-dark}},
keywordstyle = {\color{key-dark}},
keywordstyle = [2]{\color{lime}},
keywordstyle = [3]{\color{yellow}},
keywordstyle = [4]{\color{teal}},
breaklines=true,
showstringspaces=false,
tabsize=2
}

\definecolor{basic-light}{HTML}{5E6767}
\definecolor{comment-light}{HTML}{7EA36F}
\definecolor{background-light}{HTML}{FDF6E3}
\definecolor{string-light}{HTML}{F6A26B}
\definecolor{keyword-light}{HTML}{268BD2}

\lstdefinestyle{lightcode}{
language=Python,
basicstyle=\color{basic-light}\small\ttfamily,
numbers=left,
numbersep=10pt,
xleftmargin=20pt,
frame=tb,
framexleftmargin=20pt,
keywordstyle=\color{keyword-light},
commentstyle=\color{comment-light},
backgroundcolor=\color{background-light},
stringstyle=\color{string-light},
keywordstyle = [2]{\color{teal}},
keywordstyle = [3]{\color{yellow}},
keywordstyle = [4]{\color{teal}},
identifierstyle=\color{basic-light},
breaklines=true,
showstringspaces=false,
tabsize=2
}

\title{Basic example}
\subtitle{Lorem ipsum}

\date{}

\begin{document}

\begin{frame}[plain]	
	\titlepage
\end{frame}

\begin{frame}{Normal slide}
	\begin{itemize}
		\item Lorem ipsum
		\item Lorem ipsum
		\item Lorem ipsum
		\item Lorem ipsum
	\end{itemize}
\end{frame}

\begin{frame}[fragile]{Test}
    \begin{itemize}
        \item Lorem ipsum
        \item Lorem ipsum

            \begin{lstlisting}[style=lightcode]
# Python test
print('Hello world')
           \end{lstlisting}

    \end{itemize}
\end{frame}

\begin{frame}[standout, fragile]{Test}
        \begin{itemize}
		\item Lorem ipsum
		\item Lorem ipsum
		
		\begin{lstlisting}[style=darkcode]
# Python test
print('Hello world')
		\end{lstlisting}
		
    \end{itemize}
\end{frame}
\end{document}
```
I created two themes for styling code listing (darkcode and lightcode).
Btw, I tested it on Ubuntu.

**Comment by piazzai** [comment] 2024-02-21 08:51
I compiled your example without errors. The only flaw I see is that the title of the standout frame is dark but it shouldn't be. I am not sure if this is the issue you were referring to, or if something else happens on your end that does not happen on mine (Pop!_OS 22.04 LTS). What exactly is the text that retains the background color of the frame?

[fragile.pdf](https://github.com/piazzai/arguelles/files/14356762/fragile.pdf)

Edit: I just noticed that the dark title of the standout frame has nothing to do with fragile or lstlisting. I forgot to switch the color of the title of standout frames in the theme, because I wasn't thinking that these frames could have a title. I'll fix it in the next update.

**Comment by Hepek93** [comment] 2024-02-22 22:17
So I found mistake in .tex file. But I just tested now, and as you said, the problem is with the title name.
Currently as a workaround you can use this command before the standout frame:
```
	\setbeamercolor{normal text}{fg=oc-gray-0}
```
But when you want to use a normal slide, you have to call the command
```
	\setbeamercolor{normal text}{fg=oc-gray-0}
```
Complete example
```
\documentclass[aspectratio=169]{beamer}
\usepackage{xcolor}
\usepackage{listings}

\usetheme{Arguelles}

\definecolor{main-dark}{rgb}{0.6627, 0.7176, 0.7764}
\definecolor{back-dark}{rgb}{0.1686, 0.1686, 0.1686}
\definecolor{string-dark}{rgb}{0.8, 0.47, 0.196}
\definecolor{key-dark}{RGB}{53, 131, 213}
\definecolor{comment-dark}{RGB}{77,166,66} 

\lstdefinestyle{darkcode}{
	language=Python,
	basicstyle=\small\ttfamily,
	numbers=left,
	numbersep=10pt,
	xleftmargin=20pt,
	frame=tb,
	framexleftmargin=20pt,
	commentstyle=\color{comment-dark},
	backgroundcolor = {\color{back-dark}},
	stringstyle = {\color{string-dark}},
	keywordstyle = {\color{key-dark}},
	keywordstyle = [2]{\color{lime}},
	keywordstyle = [3]{\color{yellow}},
	keywordstyle = [4]{\color{teal}},
	breaklines=true,
	showstringspaces=false,
	tabsize=2
}

\definecolor{basic-light}{HTML}{5E6767}
\definecolor{comment-light}{HTML}{7EA36F}
\definecolor{background-light}{HTML}{FDF6E3}
\definecolor{string-light}{HTML}{F6A26B}
\definecolor{keyword-light}{HTML}{268BD2}

\lstdefinestyle{lightcode}{
	language=Python,
	basicstyle=\color{basic-light}\small\ttfamily,
	numbers=left,
	numbersep=10pt,
	xleftmargin=20pt,
	frame=tb,
	framexleftmargin=20pt,
	keywordstyle=\color{keyword-light},
	commentstyle=\color{comment-light},
	backgroundcolor=\color{background-light},
	stringstyle=\color{string-light},
	keywordstyle = [2]{\color{teal}},
	keywordstyle = [3]{\color{yellow}},
	keywordstyle = [4]{\color{teal}},
	identifierstyle=\color{basic-light},
	breaklines=true,
	showstringspaces=false,
	tabsize=2
}

\title{Basic example}
\subtitle{Lorem ipsum}

\date{}

\begin{document}
	
	\begin{frame}[plain]	
		\titlepage
	\end{frame}
	
	\begin{frame}{Normal slide}
		\begin{itemize}
			\item Lorem ipsum
			\item Lorem ipsum
			\item Lorem ipsum
			\item Lorem ipsum
		\end{itemize}
	\end{frame}
	
	\setbeamercolor{normal text}{fg=oc-gray-0}
	\begin{frame}[standout, fragile]{Test}
		\begin{itemize}
			\item Lorem ipsum
			\item Lorem ipsum
			
			\begin{lstlisting}[style=darkcode]
				# Python test
				print('Hello world')
			\end{lstlisting}
			
		\end{itemize}
	\end{frame}
	
	\setbeamercolor{normal text}{fg=oc-gray-8}
	\begin{frame}[fragile]{Test}
		\begin{itemize}
			\item Lorem ipsum
			\item Lorem ipsum
			
			\begin{lstlisting}[style=lightcode]
				# Python test
				print('Hello world')
			\end{lstlisting}
			
		\end{itemize}
	\end{frame}
	

\end{document}
```

Thank you!

**Comment by piazzai** [comment] 2024-02-23 09:02
Thank you for the catch.

A more straightforward solution is to edit `beamerinnerthemeArguelles.sty` and add
```
\setbeamercolor*{normal text}{fg=structure.bg}
```
to the code that styles the standout frame, starting on line 96. It is equivalent to your code, because `structure.bg` is just an alias for `oc-gray-8`. But this solution keeps your beamer code clean as you don't have to switch the color back and forth.

This solution has just been implemented, and it will be part of the next release. It might be a while before the update makes its way to CTAN. In the meantime, you could download the theme here on GitHub and put it in your `~/texmf/tex/latex` folder.

**Closed as completed by piazzai** 2024-02-23 09:02 UTC
